// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/alf4ridzi/library-crud-ent-echo/ent/books"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/schema"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	booksFields := schema.Books{}.Fields()
	_ = booksFields
	// booksDescCreatedAt is the schema descriptor for created_at field.
	booksDescCreatedAt := booksFields[7].Descriptor()
	// books.DefaultCreatedAt holds the default value on creation for the created_at field.
	books.DefaultCreatedAt = booksDescCreatedAt.Default.(func() time.Time)
	// booksDescUpdatedAt is the schema descriptor for updated_at field.
	booksDescUpdatedAt := booksFields[8].Descriptor()
	// books.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	books.DefaultUpdatedAt = booksDescUpdatedAt.Default.(func() time.Time)
	// books.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	books.UpdateDefaultUpdatedAt = booksDescUpdatedAt.UpdateDefault.(func() time.Time)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(uint) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
