// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/alf4ridzi/library-crud-ent-echo/ent/schema"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
