// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/books"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/borrowings"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/user"
)

// BorrowingsCreate is the builder for creating a Borrowings entity.
type BorrowingsCreate struct {
	config
	mutation *BorrowingsMutation
	hooks    []Hook
}

// SetBookID sets the "book_id" field.
func (_c *BorrowingsCreate) SetBookID(v uint) *BorrowingsCreate {
	_c.mutation.SetBookID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BorrowingsCreate) SetUserID(v uint) *BorrowingsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetReleaseDate sets the "release_date" field.
func (_c *BorrowingsCreate) SetReleaseDate(v time.Time) *BorrowingsCreate {
	_c.mutation.SetReleaseDate(v)
	return _c
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_c *BorrowingsCreate) SetNillableReleaseDate(v *time.Time) *BorrowingsCreate {
	if v != nil {
		_c.SetReleaseDate(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *BorrowingsCreate) SetDueDate(v time.Time) *BorrowingsCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *BorrowingsCreate) SetUser(v *User) *BorrowingsCreate {
	return _c.SetUserID(v.ID)
}

// SetBook sets the "book" edge to the Books entity.
func (_c *BorrowingsCreate) SetBook(v *Books) *BorrowingsCreate {
	return _c.SetBookID(v.ID)
}

// Mutation returns the BorrowingsMutation object of the builder.
func (_c *BorrowingsCreate) Mutation() *BorrowingsMutation {
	return _c.mutation
}

// Save creates the Borrowings in the database.
func (_c *BorrowingsCreate) Save(ctx context.Context) (*Borrowings, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BorrowingsCreate) SaveX(ctx context.Context) *Borrowings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BorrowingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BorrowingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BorrowingsCreate) check() error {
	if _, ok := _c.mutation.BookID(); !ok {
		return &ValidationError{Name: "book_id", err: errors.New(`ent: missing required field "Borrowings.book_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Borrowings.user_id"`)}
	}
	if _, ok := _c.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "Borrowings.due_date"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Borrowings.user"`)}
	}
	if len(_c.mutation.BookIDs()) == 0 {
		return &ValidationError{Name: "book", err: errors.New(`ent: missing required edge "Borrowings.book"`)}
	}
	return nil
}

func (_c *BorrowingsCreate) sqlSave(ctx context.Context) (*Borrowings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BorrowingsCreate) createSpec() (*Borrowings, *sqlgraph.CreateSpec) {
	var (
		_node = &Borrowings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(borrowings.Table, sqlgraph.NewFieldSpec(borrowings.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ReleaseDate(); ok {
		_spec.SetField(borrowings.FieldReleaseDate, field.TypeTime, value)
		_node.ReleaseDate = &value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(borrowings.FieldDueDate, field.TypeTime, value)
		_node.DueDate = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   borrowings.UserTable,
			Columns: []string{borrowings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   borrowings.BookTable,
			Columns: []string{borrowings.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(books.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BookID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BorrowingsCreateBulk is the builder for creating many Borrowings entities in bulk.
type BorrowingsCreateBulk struct {
	config
	err      error
	builders []*BorrowingsCreate
}

// Save creates the Borrowings entities in the database.
func (_c *BorrowingsCreateBulk) Save(ctx context.Context) ([]*Borrowings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Borrowings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BorrowingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BorrowingsCreateBulk) SaveX(ctx context.Context) []*Borrowings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BorrowingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BorrowingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
