// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/borrowings"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/predicate"
)

// BorrowingsUpdate is the builder for updating Borrowings entities.
type BorrowingsUpdate struct {
	config
	hooks    []Hook
	mutation *BorrowingsMutation
}

// Where appends a list predicates to the BorrowingsUpdate builder.
func (_u *BorrowingsUpdate) Where(ps ...predicate.Borrowings) *BorrowingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the BorrowingsMutation object of the builder.
func (_u *BorrowingsUpdate) Mutation() *BorrowingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BorrowingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BorrowingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BorrowingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BorrowingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BorrowingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(borrowings.Table, borrowings.Columns, sqlgraph.NewFieldSpec(borrowings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{borrowings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BorrowingsUpdateOne is the builder for updating a single Borrowings entity.
type BorrowingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BorrowingsMutation
}

// Mutation returns the BorrowingsMutation object of the builder.
func (_u *BorrowingsUpdateOne) Mutation() *BorrowingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the BorrowingsUpdate builder.
func (_u *BorrowingsUpdateOne) Where(ps ...predicate.Borrowings) *BorrowingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BorrowingsUpdateOne) Select(field string, fields ...string) *BorrowingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Borrowings entity.
func (_u *BorrowingsUpdateOne) Save(ctx context.Context) (*Borrowings, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BorrowingsUpdateOne) SaveX(ctx context.Context) *Borrowings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BorrowingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BorrowingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BorrowingsUpdateOne) sqlSave(ctx context.Context) (_node *Borrowings, err error) {
	_spec := sqlgraph.NewUpdateSpec(borrowings.Table, borrowings.Columns, sqlgraph.NewFieldSpec(borrowings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Borrowings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, borrowings.FieldID)
		for _, f := range fields {
			if !borrowings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != borrowings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Borrowings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{borrowings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
