// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/alf4ridzi/library-crud-ent-echo/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/books"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/borrowings"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/categories"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/role"
	"github.com/alf4ridzi/library-crud-ent-echo/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Books is the client for interacting with the Books builders.
	Books *BooksClient
	// Borrowings is the client for interacting with the Borrowings builders.
	Borrowings *BorrowingsClient
	// Categories is the client for interacting with the Categories builders.
	Categories *CategoriesClient
	// Role is the client for interacting with the Role builders.
	Role *RoleClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Books = NewBooksClient(c.config)
	c.Borrowings = NewBorrowingsClient(c.config)
	c.Categories = NewCategoriesClient(c.config)
	c.Role = NewRoleClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Books:      NewBooksClient(cfg),
		Borrowings: NewBorrowingsClient(cfg),
		Categories: NewCategoriesClient(cfg),
		Role:       NewRoleClient(cfg),
		User:       NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Books:      NewBooksClient(cfg),
		Borrowings: NewBorrowingsClient(cfg),
		Categories: NewCategoriesClient(cfg),
		Role:       NewRoleClient(cfg),
		User:       NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Books.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Books.Use(hooks...)
	c.Borrowings.Use(hooks...)
	c.Categories.Use(hooks...)
	c.Role.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Books.Intercept(interceptors...)
	c.Borrowings.Intercept(interceptors...)
	c.Categories.Intercept(interceptors...)
	c.Role.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BooksMutation:
		return c.Books.mutate(ctx, m)
	case *BorrowingsMutation:
		return c.Borrowings.mutate(ctx, m)
	case *CategoriesMutation:
		return c.Categories.mutate(ctx, m)
	case *RoleMutation:
		return c.Role.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BooksClient is a client for the Books schema.
type BooksClient struct {
	config
}

// NewBooksClient returns a client for the Books from the given config.
func NewBooksClient(c config) *BooksClient {
	return &BooksClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `books.Hooks(f(g(h())))`.
func (c *BooksClient) Use(hooks ...Hook) {
	c.hooks.Books = append(c.hooks.Books, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `books.Intercept(f(g(h())))`.
func (c *BooksClient) Intercept(interceptors ...Interceptor) {
	c.inters.Books = append(c.inters.Books, interceptors...)
}

// Create returns a builder for creating a Books entity.
func (c *BooksClient) Create() *BooksCreate {
	mutation := newBooksMutation(c.config, OpCreate)
	return &BooksCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Books entities.
func (c *BooksClient) CreateBulk(builders ...*BooksCreate) *BooksCreateBulk {
	return &BooksCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BooksClient) MapCreateBulk(slice any, setFunc func(*BooksCreate, int)) *BooksCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BooksCreateBulk{err: fmt.Errorf("calling to BooksClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BooksCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BooksCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Books.
func (c *BooksClient) Update() *BooksUpdate {
	mutation := newBooksMutation(c.config, OpUpdate)
	return &BooksUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BooksClient) UpdateOne(_m *Books) *BooksUpdateOne {
	mutation := newBooksMutation(c.config, OpUpdateOne, withBooks(_m))
	return &BooksUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BooksClient) UpdateOneID(id uint) *BooksUpdateOne {
	mutation := newBooksMutation(c.config, OpUpdateOne, withBooksID(id))
	return &BooksUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Books.
func (c *BooksClient) Delete() *BooksDelete {
	mutation := newBooksMutation(c.config, OpDelete)
	return &BooksDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BooksClient) DeleteOne(_m *Books) *BooksDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BooksClient) DeleteOneID(id uint) *BooksDeleteOne {
	builder := c.Delete().Where(books.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BooksDeleteOne{builder}
}

// Query returns a query builder for Books.
func (c *BooksClient) Query() *BooksQuery {
	return &BooksQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBooks},
		inters: c.Interceptors(),
	}
}

// Get returns a Books entity by its id.
func (c *BooksClient) Get(ctx context.Context, id uint) (*Books, error) {
	return c.Query().Where(books.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BooksClient) GetX(ctx context.Context, id uint) *Books {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBorrowings queries the borrowings edge of a Books.
func (c *BooksClient) QueryBorrowings(_m *Books) *BorrowingsQuery {
	query := (&BorrowingsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(books.Table, books.FieldID, id),
			sqlgraph.To(borrowings.Table, borrowings.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, books.BorrowingsTable, books.BorrowingsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCategories queries the categories edge of a Books.
func (c *BooksClient) QueryCategories(_m *Books) *CategoriesQuery {
	query := (&CategoriesClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(books.Table, books.FieldID, id),
			sqlgraph.To(categories.Table, categories.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, books.CategoriesTable, books.CategoriesPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BooksClient) Hooks() []Hook {
	return c.hooks.Books
}

// Interceptors returns the client interceptors.
func (c *BooksClient) Interceptors() []Interceptor {
	return c.inters.Books
}

func (c *BooksClient) mutate(ctx context.Context, m *BooksMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BooksCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BooksUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BooksUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BooksDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Books mutation op: %q", m.Op())
	}
}

// BorrowingsClient is a client for the Borrowings schema.
type BorrowingsClient struct {
	config
}

// NewBorrowingsClient returns a client for the Borrowings from the given config.
func NewBorrowingsClient(c config) *BorrowingsClient {
	return &BorrowingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `borrowings.Hooks(f(g(h())))`.
func (c *BorrowingsClient) Use(hooks ...Hook) {
	c.hooks.Borrowings = append(c.hooks.Borrowings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `borrowings.Intercept(f(g(h())))`.
func (c *BorrowingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Borrowings = append(c.inters.Borrowings, interceptors...)
}

// Create returns a builder for creating a Borrowings entity.
func (c *BorrowingsClient) Create() *BorrowingsCreate {
	mutation := newBorrowingsMutation(c.config, OpCreate)
	return &BorrowingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Borrowings entities.
func (c *BorrowingsClient) CreateBulk(builders ...*BorrowingsCreate) *BorrowingsCreateBulk {
	return &BorrowingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BorrowingsClient) MapCreateBulk(slice any, setFunc func(*BorrowingsCreate, int)) *BorrowingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BorrowingsCreateBulk{err: fmt.Errorf("calling to BorrowingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BorrowingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BorrowingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Borrowings.
func (c *BorrowingsClient) Update() *BorrowingsUpdate {
	mutation := newBorrowingsMutation(c.config, OpUpdate)
	return &BorrowingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BorrowingsClient) UpdateOne(_m *Borrowings) *BorrowingsUpdateOne {
	mutation := newBorrowingsMutation(c.config, OpUpdateOne, withBorrowings(_m))
	return &BorrowingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BorrowingsClient) UpdateOneID(id int) *BorrowingsUpdateOne {
	mutation := newBorrowingsMutation(c.config, OpUpdateOne, withBorrowingsID(id))
	return &BorrowingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Borrowings.
func (c *BorrowingsClient) Delete() *BorrowingsDelete {
	mutation := newBorrowingsMutation(c.config, OpDelete)
	return &BorrowingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BorrowingsClient) DeleteOne(_m *Borrowings) *BorrowingsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BorrowingsClient) DeleteOneID(id int) *BorrowingsDeleteOne {
	builder := c.Delete().Where(borrowings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BorrowingsDeleteOne{builder}
}

// Query returns a query builder for Borrowings.
func (c *BorrowingsClient) Query() *BorrowingsQuery {
	return &BorrowingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBorrowings},
		inters: c.Interceptors(),
	}
}

// Get returns a Borrowings entity by its id.
func (c *BorrowingsClient) Get(ctx context.Context, id int) (*Borrowings, error) {
	return c.Query().Where(borrowings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BorrowingsClient) GetX(ctx context.Context, id int) *Borrowings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Borrowings.
func (c *BorrowingsClient) QueryUser(_m *Borrowings) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(borrowings.Table, borrowings.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, borrowings.UserTable, borrowings.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryBook queries the book edge of a Borrowings.
func (c *BorrowingsClient) QueryBook(_m *Borrowings) *BooksQuery {
	query := (&BooksClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(borrowings.Table, borrowings.FieldID, id),
			sqlgraph.To(books.Table, books.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, borrowings.BookTable, borrowings.BookColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BorrowingsClient) Hooks() []Hook {
	return c.hooks.Borrowings
}

// Interceptors returns the client interceptors.
func (c *BorrowingsClient) Interceptors() []Interceptor {
	return c.inters.Borrowings
}

func (c *BorrowingsClient) mutate(ctx context.Context, m *BorrowingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BorrowingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BorrowingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BorrowingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BorrowingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Borrowings mutation op: %q", m.Op())
	}
}

// CategoriesClient is a client for the Categories schema.
type CategoriesClient struct {
	config
}

// NewCategoriesClient returns a client for the Categories from the given config.
func NewCategoriesClient(c config) *CategoriesClient {
	return &CategoriesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `categories.Hooks(f(g(h())))`.
func (c *CategoriesClient) Use(hooks ...Hook) {
	c.hooks.Categories = append(c.hooks.Categories, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `categories.Intercept(f(g(h())))`.
func (c *CategoriesClient) Intercept(interceptors ...Interceptor) {
	c.inters.Categories = append(c.inters.Categories, interceptors...)
}

// Create returns a builder for creating a Categories entity.
func (c *CategoriesClient) Create() *CategoriesCreate {
	mutation := newCategoriesMutation(c.config, OpCreate)
	return &CategoriesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Categories entities.
func (c *CategoriesClient) CreateBulk(builders ...*CategoriesCreate) *CategoriesCreateBulk {
	return &CategoriesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CategoriesClient) MapCreateBulk(slice any, setFunc func(*CategoriesCreate, int)) *CategoriesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CategoriesCreateBulk{err: fmt.Errorf("calling to CategoriesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CategoriesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CategoriesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Categories.
func (c *CategoriesClient) Update() *CategoriesUpdate {
	mutation := newCategoriesMutation(c.config, OpUpdate)
	return &CategoriesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CategoriesClient) UpdateOne(_m *Categories) *CategoriesUpdateOne {
	mutation := newCategoriesMutation(c.config, OpUpdateOne, withCategories(_m))
	return &CategoriesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CategoriesClient) UpdateOneID(id uint) *CategoriesUpdateOne {
	mutation := newCategoriesMutation(c.config, OpUpdateOne, withCategoriesID(id))
	return &CategoriesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Categories.
func (c *CategoriesClient) Delete() *CategoriesDelete {
	mutation := newCategoriesMutation(c.config, OpDelete)
	return &CategoriesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CategoriesClient) DeleteOne(_m *Categories) *CategoriesDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CategoriesClient) DeleteOneID(id uint) *CategoriesDeleteOne {
	builder := c.Delete().Where(categories.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CategoriesDeleteOne{builder}
}

// Query returns a query builder for Categories.
func (c *CategoriesClient) Query() *CategoriesQuery {
	return &CategoriesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCategories},
		inters: c.Interceptors(),
	}
}

// Get returns a Categories entity by its id.
func (c *CategoriesClient) Get(ctx context.Context, id uint) (*Categories, error) {
	return c.Query().Where(categories.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CategoriesClient) GetX(ctx context.Context, id uint) *Categories {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBooks queries the books edge of a Categories.
func (c *CategoriesClient) QueryBooks(_m *Categories) *BooksQuery {
	query := (&BooksClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(categories.Table, categories.FieldID, id),
			sqlgraph.To(books.Table, books.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, categories.BooksTable, categories.BooksPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CategoriesClient) Hooks() []Hook {
	return c.hooks.Categories
}

// Interceptors returns the client interceptors.
func (c *CategoriesClient) Interceptors() []Interceptor {
	return c.inters.Categories
}

func (c *CategoriesClient) mutate(ctx context.Context, m *CategoriesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CategoriesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CategoriesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CategoriesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CategoriesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Categories mutation op: %q", m.Op())
	}
}

// RoleClient is a client for the Role schema.
type RoleClient struct {
	config
}

// NewRoleClient returns a client for the Role from the given config.
func NewRoleClient(c config) *RoleClient {
	return &RoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `role.Hooks(f(g(h())))`.
func (c *RoleClient) Use(hooks ...Hook) {
	c.hooks.Role = append(c.hooks.Role, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `role.Intercept(f(g(h())))`.
func (c *RoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.Role = append(c.inters.Role, interceptors...)
}

// Create returns a builder for creating a Role entity.
func (c *RoleClient) Create() *RoleCreate {
	mutation := newRoleMutation(c.config, OpCreate)
	return &RoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Role entities.
func (c *RoleClient) CreateBulk(builders ...*RoleCreate) *RoleCreateBulk {
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RoleClient) MapCreateBulk(slice any, setFunc func(*RoleCreate, int)) *RoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RoleCreateBulk{err: fmt.Errorf("calling to RoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Role.
func (c *RoleClient) Update() *RoleUpdate {
	mutation := newRoleMutation(c.config, OpUpdate)
	return &RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RoleClient) UpdateOne(_m *Role) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRole(_m))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RoleClient) UpdateOneID(id int) *RoleUpdateOne {
	mutation := newRoleMutation(c.config, OpUpdateOne, withRoleID(id))
	return &RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Role.
func (c *RoleClient) Delete() *RoleDelete {
	mutation := newRoleMutation(c.config, OpDelete)
	return &RoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RoleClient) DeleteOne(_m *Role) *RoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RoleClient) DeleteOneID(id int) *RoleDeleteOne {
	builder := c.Delete().Where(role.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RoleDeleteOne{builder}
}

// Query returns a query builder for Role.
func (c *RoleClient) Query() *RoleQuery {
	return &RoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRole},
		inters: c.Interceptors(),
	}
}

// Get returns a Role entity by its id.
func (c *RoleClient) Get(ctx context.Context, id int) (*Role, error) {
	return c.Query().Where(role.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RoleClient) GetX(ctx context.Context, id int) *Role {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Role.
func (c *RoleClient) QueryUser(_m *Role) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(role.Table, role.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, role.UserTable, role.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RoleClient) Hooks() []Hook {
	return c.hooks.Role
}

// Interceptors returns the client interceptors.
func (c *RoleClient) Interceptors() []Interceptor {
	return c.inters.Role
}

func (c *RoleClient) mutate(ctx context.Context, m *RoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Role mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uint) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uint) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uint) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uint) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryBorrowings queries the borrowings edge of a User.
func (c *UserClient) QueryBorrowings(_m *User) *BorrowingsQuery {
	query := (&BorrowingsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(borrowings.Table, borrowings.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.BorrowingsTable, user.BorrowingsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRole queries the role edge of a User.
func (c *UserClient) QueryRole(_m *User) *RoleQuery {
	query := (&RoleClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, user.RoleTable, user.RoleColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	hooks := c.hooks.User
	return append(hooks[:len(hooks):len(hooks)], user.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	inters := c.inters.User
	return append(inters[:len(inters):len(inters)], user.Interceptors[:]...)
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Books, Borrowings, Categories, Role, User []ent.Hook
	}
	inters struct {
		Books, Borrowings, Categories, Role, User []ent.Interceptor
	}
)
